### ISSUE TITLE
Crash happens after running python producer.py

### ISSUE THREAD

**Issue by lipeng28** [apache/rocketmq-client-python#106]
Hi There

When I run 'python producer.py' I got the following error, do you have any ideas why it happens?

Traceback (most recent call last):
  File "producer.py", line 11, in <module>
    ret = producer.send_sync(msg)
  File "/home/lipeng/.pyenv/versions/3.7.2/lib/python3.7/site-packages/rocketmq/client.py", line 210, in send_sync
    ffi_check(dll.SendMessageSync(self._handle, msg, ctypes.pointer(c_result)))
  File "/home/lipeng/.pyenv/versions/3.7.2/lib/python3.7/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
rocketmq.exceptions.ProducerSendSyncFailed: No route info of this topic: abc-topic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp line:418

Thanks
Peng

**Comment by ifplusor** [comment]
link apache/rocketmq-client-cpp#325 apache/rocketmq-client-cpp#346

**Comment by lipeng28** [comment]
I resolved the issue through adding topic into the broker, I used the python client.

**Comment by ruojiruoji** [comment]
> I resolved the issue through adding topic into the broker, I used the python client.

Hi, isn't the topic automatically created in the broker when sending the message from the producer? Why do you need to manually add the topic into the broker? Thanks
