### ISSUE TITLE
consumer启动报错

### ISSUE THREAD

**Issue by HQ1363** [apache/rocketmq-client-python#109]
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: Permission denied: "/root/logs/rocketmq-cpp/"

**Comment by HQ1363** [comment]
更改/root/logs目录的权限后,  问题得以解决

**Comment by francisoliverlee** [comment]
i would close the issue, feel free to reopen it.
