### ISSUE TITLE
librocketmq.so: undefined symbol: CreateOrderlyProducer

### ISSUE THREAD

**Issue by tankcong** [apache/rocketmq-client-python#115]
**BUG REPORT**

1. Please describe the issue you observed:

running samples/producer.py with error:

> Traceback (most recent call last):
  File "producer.py", line 19, in <module>
    from rocketmq.client import Producer, Message, TransactionMQProducer, TransactionStatus
  File "/usr/local/lib64/python3.6/site-packages/rocketmq/client.py", line 24, in <module>
    from .ffi import (
  File "/usr/local/lib64/python3.6/site-packages/rocketmq/ffi.py", line 173, in <module>
    dll.CreateOrderlyProducer.argtypes = [c_char_p]
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 356, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 361, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib64/python3.6/site-packages/rocketmq/librocketmq.so: undefined symbol: CreateOrderlyProducer

2. Please tell us about your environment:

 - CentOS 7
 - python 3.7
 - rocketmq-client-python 1.2.4
 - rocketmq version 4.8.0
 - rocketmq-client-cpp 2.0.0 -centos7-x86_64

**Comment by ifplusor** [comment]
Please use latest rocketmq-client-cpp

**Comment by ifplusor** [comment]
Check the declaration of `CreateOrderlyProducer` in [CProducer.h](https://github.com/apache/rocketmq-client-cpp/blob/master/include/CProducer.h)

**Comment by treelly** [comment]
I have the same problem, my system is linux-ubuntu, how did you solve it

**Comment by missuor** [comment]
same problem 
ubuntu 20.04
```
(ecloud-collector) root@think:~# python -V
Python 2.7.18
(ecloud-collector) root@think:~# pip list
Package                Version
---------------------- ---------
backports-abc          0.5
canal-python           0.4
certifi                2021.10.8
chardet                4.0.0
enum34                 1.1.10
futures                3.3.0
idna                   2.10
pip                    20.3.4
protobuf               3.17.3
requests               2.27.1
rocketmq               0.4.4
rocketmq-client-python 2.0.0
setuptools             44.1.1
singledispatch         3.7.0
six                    1.16.0
tornado                5.1.1
typing                 3.10.0.0
urllib3                1.26.8
wheel                  0.37.1
(ecloud-collector) root@think:~# dpkg -l|grep rocketmq
ii  rocketmq                                   2.0.0                               amd64        This package is C++ client of Apache RocketMQ for debian and its derivertives like Ubuntu.
(ecloud-collector) root@think:~# 
```

**Comment by treelly** [comment]
您好，邮件已收到！

**Comment by thomaslv2** [comment]
@missuor You have installed other rocketmq client-rocketmq, you can try:
pip uninstall rocketmq
pip install rocketmq-client-python
Hope this works for you！

**Comment by fei-ghb** [comment]
install rocketmq-client-cpp-2.0.0-centos7-x86_64

**Comment by treelly** [comment]
您好，邮件已收到！

**Comment by Ava-yjt** [comment]
卸载rocketmq-client-python和rocketmq
重新安装rocketmq-client-python和rocketmq-client-cpp，成功解决了这个问题
猜测是新版的rocketmq-client-python和rocketmq包有冲突，只需要安装前者就行

**Comment by treelly** [comment]
您好，邮件已收到！
