### ISSUE TITLE
advice: add a branch to build the client of Python 3.6

### ISSUE THREAD

**Issue by naah69** [apache/rocketmq-client-python#26]
advice: add a branch to build the client of Python 3.6.
i try to build the client of Python 3.7.
but i failed.

i modify the cmake.
but it show this message：Missing Library: python-devel
![image](https://user-images.githubusercontent.com/25682169/51164248-51262380-18d7-11e9-992e-236a56e65b9b.png)

when i try to find the python-devel.
i only found the python-devel 2.7.

**Comment by ShannonDing** [comment]
Good idea, a new branch used for Python 3.X developing will be created soon.
