### ISSUE TITLE
question：about compile of this python client

### ISSUE THREAD

**Issue by elisium7** [apache/rocketmq-client-python#34]
1/编译出来的librocketmqclientpython.a可以怎么使用么？

2/使用cmake ../  -DROCKETMQ_USE_STATIC_LIBS=ON编译时，出来的librocketmqclientpython.so包有问题，会有undefind symbol:_ZN5boost6detail16thread_data_baseE等似乎是boost库链接的错误? 但是我用librockemq.a去编译c++的demo时没有问题。

3/使用cmake ../  -DROCKETMQ_USE_STATIC_LIBS=OFF编译时，涉及到so包的二次依赖，除了在/etc/ld.so.conf添加搜索路径，还有什么好方法不？感觉这样不是太方便。

**Comment by francisoliverlee** [comment]
if you need librocketmqclientpython .so, mail me: 1026203200@qq.com

**Comment by 2h4dl** [comment]
I  have an issue same as you.
If you solved, please tell me.
