### ISSUE TITLE
consume message so late after client startup(7min late)

### ISSUE THREAD

**Issue by francisoliverlee** [apache/rocketmq-client-python#36]
The issue tracker is **ONLY** used for the python client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
start consumer nomally

- What did you expect to see?
7min after consumer startup,  consumer start consume message

- What did you see instead?
consume meesgae as soon as consumer startup

2. Please tell us about your environment:

 - What is your OS?
centos

 - What is your client version?
1.2

 - What is your RocketMQ version?

4.2

- other env
8 queue in tatol
there are 3000+ message not consumed in one queue, no diff in other queues

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ShannonDing** [comment]
FYI: https://github.com/apache/rocketmq-client-cpp/issues/132
