### ISSUE TITLE
Build error on MacOS platform.

### ISSUE THREAD

**Issue by kulallwang** [apache/rocketmq-client-python#37]
报错信息如下：

[ 50%] Linking CXX shared library ../../bin/librocketmqclientpython.so
cd /Users/kula/Documents/project/pylibs/rocketmq-client-python/build/project && /usr/local/Cellar/cmake/3.14.1/bin/cmake -E cmake_link_script CMakeFiles/rocketmqclientpython_shared.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++ -std=c++11 -g -Wall -Wno-deprecated -fPIC -fno-strict-aliasing -Wno-unused-result -Wno-unused-local-typedef -m64 -O3 -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -fPIC -shared -o ../../bin/librocketmqclientpython.so -install_name @rpath/librocketmqclientpython.so CMakeFiles/rocketmqclientpython_shared.dir/__/src/PythonWrapper.cpp.o -lpthread -ldl -lz /usr/local/lib/librocketmq.a /usr/local/lib/libboost_python.a /usr/lib/libpython2.7.dylib 
Undefined symbols for architecture x86_64:
  "Json::FastWriter::write(Json::Value const&)", referenced from:
      rocketmq::HeartbeatData::Encode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in librocketmq.a(MQClientAPIImpl.cpp.o)
      rocketmq::ConsumerRunningInfo::encode() in librocketmq.a(ConsumerRunningInfo.cpp.o)
      rocketmq::RemotingCommand::Encode() in librocketmq.a(RemotingCommand.cpp.o)
      rocketmq::LockBatchRequestBody::Encode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in librocketmq.a(LockBatchBody.cpp.o)
      rocketmq::UnlockBatchRequestBody::Encode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in librocketmq.a(LockBatchBody.cpp.o)
  "Json::FastWriter::FastWriter()", referenced from:
      rocketmq::HeartbeatData::Encode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in librocketmq.a(MQClientAPIImpl.cpp.o)

**Comment by ShannonDing** [comment]
This error "Undefined symbols for architecture x86_64" occur, Which static library do you use? for step by step build, please refer to https://github.com/apache/rocketmq-client-python/blob/master/doc/Introduction.md .

**Comment by kulallwang** [comment]
I follow the introduction step by step. Build using Dynamic RocketMQ and boost python libraries is ok. But build using static libraries is failed.

**Comment by ShannonDing** [comment]
there is some error on mac platform when packaging CPP static library, So the dynamic library is recommended to use.
