### ISSUE TITLE
How to use it correctly in rocketmq-python-client to ensure at least one time or just once

### ISSUE THREAD

**Issue by qqizai** [apache/rocketmq-client-python#43]
The issue tracker is **ONLY** used for the python client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
    Example of using the official website pullconsumer or pushconsumer
- What did you expect to see?
     Spend at least once or just once, and process the msg of the transaction failure, then msg roll back, wait for the next try again
- What did you see instead?
    read all msg repeatedly every time you start
2. Please tell us about your environment:

 - What is your OS?
      ubuntu 18.04
 - What is your client version?
      0.4.1
 - What is your RocketMQ version?
      4.5.2
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
    I want to know the following two usages：
    （1）How can I use it properly to ensure that I consume it at least once or just once, 
    （2）and how the message queue is rolled back when the transaction fails.
   Looking forward to your reply，thanks.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
  
4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by francisoliverlee** [comment]
there are some dfferent between at least one time and once. 
now support at-least-one-time

**Comment by lvsunshine21** [comment]
if I use PushConsumer,how can I  get messages from offset where last time I committed?I need to remember the offset to local machine?

**Comment by francisoliverlee** [comment]
> if I use PushConsumer, how can I get messages from offset were last time I committed? I need to remember the offset to the local machine?

it's up to messageModel.
Clustering: offset stored in broker
BROADCASTING: offset stored in local files

cn doc : https://github.com/apache/rocketmq/blob/master/docs/cn/best_practice.md
en doc: https://github.com/apache/rocketmq/blob/master/docs/en/Operations_Consumer.md
