### ISSUE TITLE
I hope to add python3.x or add go-client later.

### ISSUE THREAD

**Issue by wangguanfu** [apache/rocketmq-client-python#44]
I hope I can add the version of python3.x later.
 Or can you add go-client?

**Comment by ShannonDing** [comment]
GJ!
there is a branch named "python3" to support the version 3.X. it is better if you can submit your code to this branch and then call for a review.

**Comment by ShannonDing** [comment]
for another question, also you can find the go repo [here](https://github.com/apache/rocketmq-client-go).
