### ISSUE TITLE
Boost.Python.ArgumentError: Python argument types in     librocketmqclientpython.RegisterMessageCallback(void*, function, NoneType)

### ISSUE THREAD

**Issue by wzk784533** [apache/rocketmq-client-python#45]
Traceback (most recent call last):
  File "testmq.py", line 30, in <module>
    RegisterMessageCallback(consumer, consumerMessage, None)
Boost.Python.ArgumentError: Python argument types in
    librocketmqclientpython.RegisterMessageCallback(void*, function, NoneType)
did not match C++ signature:
    RegisterMessageCallback(void*, _object*)

**Comment by francisoliverlee** [comment]
@wzk784533 show your codes pls
