### ISSUE TITLE
producer.setToken

### ISSUE THREAD

**Issue by MonkeyMajik** [apache/rocketmq-client-python#47]
I wanna konw how to set Token for producer？ Thanks

**Comment by ifplusor** [comment]
What is Token? ONS or ACL?

**Comment by MonkeyMajik** [comment]
I mean    rockmq for java has a function  producer.setToken   but in python cant find it. also in cpp

**Comment by ifplusor** [comment]
@MonkeyMajik i don't see it in https://github.com/apache/rocketmq
