### ISSUE TITLE
raise ImportError('rocketmq dynamic library not found')

### ISSUE THREAD

**Issue by TonyK-T** [apache/rocketmq-client-python#77]
i got this msg,why ??????
what shoud i do???

from .ffi import (
  File "/usr/local/lib/python3.6/dist-packages/rocketmq_client_python-0.5.0rc3-py3.6.egg/rocketmq/ffi.py", line 40, in <module>
    raise ImportError('rocketmq dynamic library not found')
ImportError: rocketmq dynamic library not found

**Comment by TonyK-T** [comment]
PC info: 
Distributor ID:	LinuxMint
Description:	Linux Mint 19.2 Tina
Release:	19.2
Codename:	tina
python3.6

**Comment by tinybright** [comment]
@TonyK-T maybe you can try to pip install rocketmq first.

**Comment by TonyK-T** [comment]
> pip install rocketmq

pip install rocketmq  &&     use ".set_namesrv_addr"  not ".set_name_server_address"   
make successful,
tks

**Comment by ShannonDing** [comment]
the

> > pip install rocketmq
> 
> pip install rocketmq && use ".set_namesrv_addr" not ".set_name_server_address"
> make successful,
> tks

the version 2.0.0 has been released, and the method "set_name_server_address" can be used directly.

**Comment by ShannonDing** [comment]
for the latest release, pls refer to https://pypi.org/project/rocketmq-client-python/

**Comment by zhukangfeng** [comment]
> for the latest release, pls refer to https://pypi.org/project/rocketmq-client-python/

2.0.0 has the same error `raise ImportError('rocketmq dynamic library not found')`

when installing by `pip install rocketmq-client-python`, the necessary cpp library does not been installed.

**Comment by ShannonDing** [comment]
the CPP kernel will not be installed by the pip install script. 
it should be installed manually.
