### ISSUE TITLE
What should I put in expression ? consumer.subscribe(topic, callback,expression) 

### ISSUE THREAD

**Issue by tinybright** [apache/rocketmq-client-python#78]
I used  p1 and *pi1*  to   subscribe message with tags p1,but I can get nothing.

**Comment by ShannonDing** [comment]
hello, could you please share the code on subscribing messages?

**Comment by tinybright** [comment]
I tried to reappear it.
But it went wrong when I tried to send msg by Producer.
Though I can send Message By rocketmq-console.
The result is that subscribe go wrong  after I kill the process directly and rerun a consumer by same group_id  and instance_name.

`interval_second = 4
rocketmq_config = Config.rocketmq
namesrv = rocketmq_config['namesrv']
topic = rocketmq_config['topic']
producer_group_id = rocketmq_config['producer_group_id']
tags='seed'
keys='seed'
producer = Producer(producer_group_id)
producer.start()

# logger = Tools.get_logger('gogo')

def fetch_id(seed):
    return seed is None and None or str(seed['id'])

def job1():
    seed_list = ["1","2"]
    producer.set_namesrv_addr(namesrv)
    i = 0
    print("tick {0} {1}".format(topic,datetime.datetime.now()))
    for seed in range(4):

        i += 1
        msg = Message(topic)
        msg.set_keys('pk{0}'.format(i))
        msg.set_tags('pt{0}'.format(i))
        t = datetime.datetime.now().strftime("%M%S"+"-"+str(i))
        msg.set_body( t)
        ret = producer.send_sync(msg)
        print(t,ret.status, ret.msg_id, ret.offset)


def job1_task():
    threading.Thread(target=job1).start()

def run():
    job1_task()
    schedule.every(interval_second).seconds.do(job1_task)
    while True:
        schedule.run_pending()
    producer.shutdown()

run()`
`Exception in thread Thread-51:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "gogo_producer1.py", line 47, in job1
    ret = producer.send_sync(msg)
  File "/usr/lib64/python3.6/site-packages/rocketmq/client.py", line 214, in send_sync
    ffi_check(dll.SendMessageSync(self._handle, msg, ctypes.pointer(cres)))
  File "/usr/lib64/python3.6/site-packages/rocketmq/exceptions.py", line 27, in ffi_check
    raise exc_cls(msg)
rocketmq.exceptions.ProducerSendSyncFailed: No route info of this topic: SpiderSeed,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducer.cpp line:379`

**Comment by ShannonDing** [comment]
The error shows that the client failed to get the route of the topic. 
please make sure that the name server be set before the producer being started.
you can follow the [samples](https://github.com/apache/rocketmq-client-python/tree/master/samples) and have a try.

**Comment by tinybright** [comment]
It's my mistake.I adjusted the code and put the start before set_namesrv_addr.

**Comment by tinybright** [comment]
It works fine after I use a new group_id and instance_name per run.I don't know if it's going to cause any other problems.

**Comment by designer-app** [comment]
@tinybright @ShannonDing  hello, can you tell how to set instance_id ? I found no API to set the instance_id when I am trying to connect Aliyun rocketmq. It's appreciated if code sample is provided!

**Comment by ifplusor** [comment]
@designer-app Please see https://github.com/apache/rocketmq-client-python/blob/d074515b0104354d1b54ad53a110e49413f8d889/rocketmq/client.py#L236 and https://github.com/apache/rocketmq-client-python/blob/d074515b0104354d1b54ad53a110e49413f8d889/rocketmq/client.py#L438

**Comment by designer-app** [comment]
thanks. But pip install rocketmq-client will only install version 2.0.0, which doesn't have such API set_instance_name in Producer.  And I am using rocketmq-client-ccp 2.0.0 too! 
When I connect to Aliyun RocketMQ via TCP, it will throw exception "No route info of this topic".
Any suggestion to solve it ?

**Comment by bifeng** [comment]
Same issue too.

**Comment by designer-app** [comment]
> 

we need to download the how project  and install the client manually.
cannot use the pip install

**Comment by ohzhangluoluo** [comment]
@designer-app hello, could you please tell me what is the how project?
