### ISSUE TITLE
Repeatly consume mesages with error throw.

### ISSUE THREAD

**Issue by ysjjovo** [apache/rocketmq-client-python#88]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
start nameserver and broker.
run python client producer sample produce a message.
run python client consumer sample consume message.
- What did you expect to see?
produce one meesage then consume one message
- What did you see instead?
repeatly consume on message with error throw below
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/Users/Lin/app/openwhisk-package-kafka/venv/lib/python2.7/site-packages/rocketmq/client.py", line 405, in _on_message
    raise exc
ValueError: Consume status error, please use enum 'ConsumeStatus' as response  File "/Users/Lin/app/openwhisk-package-kafka/venv/lib/python2.7/site-packages/rocketmq/client.py", line 405, in _on_message
    raise exc
ValueError: Consume status error, please use enum 'ConsumeStatus' as response
```
2. Please tell us about your environment:

 - What is your OS?
MAC OSX 10.14.6
 - What is your client version?
2.0.0
 - What is your RocketMQ version?
4.7.0

**Comment by messense** [comment]
Your consumer callback function needs to return a `ConsumeStatus` as response.

**Comment by ysjjovo** [comment]
Thanks for your reply,I create a PR to fix 'README.md'
