### ISSUE TITLE
关于如何关闭 /root/logs/rocketmq-cpp日志的问题?

### ISSUE THREAD

**Issue by huajason** [apache/rocketmq-client-python#92]

**Comment by messense** [comment]
这个需要上游 rocketmq-client-cpp 支持配置，可以去提个 issue.

**Comment by huajason** [comment]
@messense 好的, 还有个问题, 关于producer的使用
1. 在web服务器里, 应该是发送消息时创建实例,  发完就 shutdown, 还是应该创建一个producer实例
2. 如果是一直用这个实例, 我应该在web服务器退出时shutdown呢

**Comment by messense** [comment]
@huajason 
1. 创建一个 producer 实例然后复用
2. 实例销毁的时候应该会自动 shutdown，不放心也可以用 atexit 注册个 hook 进程退出的时候 shutdown

**Comment by huajason** [comment]
@messense 我的web程序使用flask框架跑的, 我用signal监听退出信号时shutdown producer, 但是程序仍会卡住, 除非kill -9

**Comment by messense** [comment]
@huajason Web App 的 supervisor 比如 supervisord/systemd 应该可以配置 graceful shutdown，停止等 30s 还没退出就会自动发 kill -9

**Comment by huajason** [comment]
@messense docker跑的, 默认10s会自动强杀, 只是希望能正常退出, 可是不行

**Comment by ifplusor** [comment]
@huajason 程序里有同时使用 consumer 吗？
@messense ctype 我不太了解，shutdown 的时候有释放 GIL 吗？

**Comment by huajason** [comment]
@ifplusor 用的一个全局变量存储的producer, 没有用consumer

**Comment by messense** [comment]
@ifplusor ctypes 调用 C API 的时候会释放 GIL

https://docs.python.org/3/library/ctypes.html#ctypes.CFUNCTYPE

**Comment by messense** [comment]
@huajason 可以贴一下 shutdown 的时候的 rocketmq-cpp 的日志、strace 下 shutdown 时候的进程看看系统调用。

**Comment by francisoliverlee** [comment]
@huajason cpp log help python-users solve problems, why you want to shutdown log output?
