### ISSUE TITLE
Multi Namesrv Error/ 跨集群通信错误

### ISSUE THREAD

**Issue by sicklife** [apache/rocketmq-client-python#94]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
  在同一个进程内，启动2个producer，向两个集群推数据，第二个创建的producer会覆盖第一个producer 的name_server 设置。

- What did you expect to see?
可以同时向两个集群推送消息

- What did you see instead?
只有第二个producer推送成功。

2. Please tell us about your environment:

 - What is your OS?
centos7/python3.8

 - What is your client version?
latest

 - What is your RocketMQ version?
不知道/unknown

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
无/No
- ...

**Comment by messense** [comment]
> 消费成功，推送失败

`推送失败` 有任何错误日志吗？

**Comment by ifplusor** [comment]
@sicklife 连接不同集群要修改 instanceName

**Comment by sicklife** [comment]
> @sicklife 连接不同集群要修改 instanceName

咋改。。。。

**Comment by sicklife** [comment]
> @sicklife 连接不同集群要修改 instanceName

我记得你和我说过。。。

**Comment by sicklife** [comment]
> @sicklife 连接不同集群要修改 instanceName

我找到了，明天试试。

**Comment by sicklife** [comment]
可以了。 `consumer.set_instance_name(str(uuid.uuid1())) `就行了。 @ifplusor 谢谢。

**Comment by sicklife** [comment]
我提交了一个pr。感谢 @ifplusor  的指导。 #95
