### ISSUE TITLE
rocketmq.exceptions.ProducerSendSyncFailed

### ISSUE THREAD

**Issue by ghost** [apache/rocketmq-client-python#97]
File "/usr/local/lib/python3.6/dist-packages/rocketmq/client.py", line 210, in send_sync
    ffi_check(dll.SendMessageSync(self._handle, msg, ctypes.pointer(c_result)))
  File "/usr/local/lib/python3.6/dist-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
rocketmq.exceptions.ProducerSendSyncFailed: None

~/logs/rocketmq-cpp log:
[rocketmq_client.log](https://github.com/apache/rocketmq-client-python/files/5061613/rocketmq_client.log)

os: ubuntu
rocketmq-client-cpp version:2.0.0

**Comment by francisoliverlee** [comment]
it seems  failr to get topic info from namesrv, so send fails too.

**Comment by francisoliverlee** [comment]
try check the network

**Comment by ifplusor** [comment]
I think the rocketmq_client.log is not cpp log file.

**Comment by messense** [comment]
I think we should just close this issue, the user deleted his/her account and is now a ghost user.

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/deleting-your-user-account
